write_host_key(:path => '/etc/ssh/id_ecdsa', :content => -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAaAAAABNlY2RzYS
1zaGEyLW5pc3RwMjU2AAAACG5pc3RwMjU2AAAAQQTyDQPyqpkQkMyVOS9ajHL4CGthtfUr
NWYI0KUNDriIumAkbjs5iNHi89dIgo2xSY14tcMbJOgu0xwcamMg/B6zAAAAuKLrIv6i6y
L+AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPINA/KqmRCQzJU5
L1qMcvgIa2G19Ss1ZgjQpQ0OuIi6YCRuOzmI0eLz10iCjbFJjXi1wxsk6C7THBxqYyD8Hr
MAAAAhAIZuPgmpriWNxMXG3OaoKhcNgWUc39eY9IXAU4D1z6x8AAAAG2FiaGlzaGVrbXVu
Z2hhdGUwQGdhbWlsLmNvbQECAwQ=
-----END OPENSSH PRIVATE KEY-----, :mode => 0600 :owner => deploy :group => www-data)
